#!/usr/bin/env bash
set -euo pipefail

TRACKING_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PROJECT_ROOT="$(cd "$TRACKING_DIR/../.." && pwd)"
SESSION_FILE="$TRACKING_DIR/SESSION.md"
LOG_FILE="$TRACKING_DIR/LOG.md"
STATE_FILE="$TRACKING_DIR/STATE.json"
DECISIONS_FILE="$TRACKING_DIR/DECISIONS.md"
CHECKPOINTS_FILE="$TRACKING_DIR/CHECKPOINTS.md"

MISSING=0
for cmd in ckpt git; do
    if ! command -v "$cmd" &>/dev/null 2>&1; then
        echo "ERROR: $cmd is required but not installed." >&2
        MISSING=1
    fi
done
[ "$MISSING" -eq 1 ] && exit 1

ensure_ckpt_session() {
    if ! ckpt steps &>/dev/null 2>&1; then
        ckpt start 2>/dev/null || true
    fi
}

start_session() {
    local goal="$*"
    if [ -z "$goal" ]; then
        echo "Usage: session.sh start \"Goal description\""
        exit 1
    fi

    echo "Starting session: $goal"
    ckpt start 2>/dev/null || true

    cat > "$SESSION_FILE" <<EOF
# Session Tracker

---

## Goal
$goal

---

## Progress

### Done
- [ ] (none yet)

### In Progress
- [ ] (none yet)

### Blocked
- [ ] (none yet)

---

## Key Decisions

| # | Decision | Rationale | Alternatives |
|---|----------|-----------|--------------|
|   |          |           |              |

---

## Critical Context

[Things the next agent absolutely needs to know before continuing.]

---

## Relevant Files

| File | Purpose | Status |
|------|---------|--------|
|      |         |        |
EOF

    echo "{\"session_goal\": \"$goal\", \"status\": \"active\", \"started_at\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\", \"steps\": 0}" > "$STATE_FILE"
    echo "Session started. SESSION.md and STATE.json written."
}

snap() {
    local msg="$*"
    if [ -z "$msg" ]; then
        echo "Usage: session.sh snap \"What you're about to do\""
        exit 1
    fi

    ensure_ckpt_session

    echo "Creating checkpoint: $msg"
    ckpt snap "$msg"

    local step_num step_hash
    step_num=$(ckpt steps 2>/dev/null | grep -c "Step" 2>/dev/null || echo "?")
    step_hash=$(ckpt steps 2>/dev/null | tail -1 | sed 's/.*\[\([a-f0-9]*\)\].*/\1/' 2>/dev/null || echo "")

    local session_date
    session_date="$(date -u +%Y-%m-%d)"

    if [ -n "$step_hash" ]; then
        if ! grep -q "$step_hash" "$CHECKPOINTS_FILE" 2>/dev/null; then
            echo "| $step_num | $step_num | $msg | $step_hash | $session_date |" >> "$CHECKPOINTS_FILE"
        fi
    fi

    local current_steps
    current_steps=$(python3 -c "import json; d=json.load(open('$STATE_FILE')); print(d.get('steps',0))" 2>/dev/null || echo "0")
    local new_steps=$((current_steps + 1))
    python3 -c "
import json
d = json.load(open('$STATE_FILE'))
d['steps'] = $new_steps
d['last_step'] = '$msg'
d['last_checkpoint'] = '$step_hash'
json.dump(d, open('$STATE_FILE', 'w'), indent=2)
" 2>/dev/null || true

    echo ""
    echo "=== REMINDER: Update SESSION.md progress section ==="
    echo "Edit $SESSION_FILE to reflect what just changed."
    echo "===================================================="
}

sync_checkpoints() {
    echo "Syncing checkpoint registry..."

    ensure_ckpt_session

    local session_date
    session_date="$(date -u +%Y-%m-%d)"

    cat > "$CHECKPOINTS_FILE" <<EOF
# Checkpoint Registry

> Maps ckpt step IDs to git hashes and session context.
> Regenerated by \`session.sh sync\`. Do not hand-edit.

| # | Step | Message | Git Hash | Date |
|---|------|---------|----------|------|
EOF

    ckpt steps 2>/dev/null | while IFS= read -r line; do
        local step_num step_hash msg
        step_num=$(echo "$line" | grep -oE 'Step [0-9]+' | sed 's/Step //' || echo "")
        step_hash=$(echo "$line" | grep -oE '\[[a-f0-9]+\]' | tr -d '[]' || echo "")
        msg=$(echo "$line" | sed 's/.*Step [0-9]*  //' | sed 's/ *\[.*//' || echo "")
        if [ -n "$step_num" ]; then
            echo "| $step_num | $step_num | $msg | $step_hash | $session_date |" >> "$CHECKPOINTS_FILE"
        fi
    done

    echo "Checkpoints synced to CHECKPOINTS.md"
}

decide() {
    local title="$1"
    local rationale="$2"
    local alternatives="$3"

    if [ -z "$title" ]; then
        echo "Usage: session.sh decide \"Title\" \"Rationale\" \"Alternatives\""
        echo "  or:  session.sh decide (interactive mode not supported — write to DECISIONS.md manually)"
        exit 1
    fi

    local session_date
    session_date="$(date -u +%Y-%m-%d)"

    cat >> "$DECISIONS_FILE" <<EOF

## $session_date — $title

**Decision:** $title
**Rationale:** $rationale
**Alternatives considered:** $alternatives
**Consequences:** (document in SESSION.md)
**Related:** 

EOF

    echo "Decision logged in DECISIONS.md"
}

end_session() {
    echo "Ending session..."

    ensure_ckpt_session

    sync_checkpoints

    if [ -f "$SESSION_FILE" ]; then
        local goal
        goal=$(python3 -c "import json; print(json.load(open('$STATE_FILE')).get('session_goal', 'Unknown goal'))" 2>/dev/null || echo "Unknown goal")
        local session_date
        session_date="$(date -u +%Y-%m-%d)"

        cat >> "$LOG_FILE" <<EOF

## $session_date — $goal

- **Duration:** (fill in)
- **Goal:** $goal
- **Done:**
  - (see SESSION.md for full progress)
- **Decisions:**
  - (see DECISIONS.md for full decision log)
- **Next steps:** (fill in)
EOF

        echo "Session appended to LOG.md"
    fi

    ckpt end 2>/dev/null || echo "ckpt end skipped (no active session or already ended)"

    cat > "$SESSION_FILE" <<EOF
# Session Tracker

> Active session state. Reset when a new session begins. See LOG.md for history.

---

## Goal

[What are we trying to accomplish this session?]

---

## Progress

### Done
- [ ] (none yet)

### In Progress
- [ ] (none yet)

### Blocked
- [ ] (none yet)

---

## Key Decisions

| # | Decision | Rationale | Alternatives |
|---|----------|-----------|--------------|
|   |          |           |              |

---

## Critical Context

[Things the next agent absolutely needs to know before continuing.]

---

## Relevant Files

| File | Purpose | Status |
|------|---------|--------|
|      |         |        |
EOF

    echo "{\"session_goal\": \"\", \"status\": \"ended\", \"ended_at\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\", \"steps\": 0}" > "$STATE_FILE"
    echo "Session ended. SESSION.md reset. Ready for next session."
}

status() {
    echo "=== Session Status ==="
    if [ -f "$STATE_FILE" ]; then
        python3 -m json.tool "$STATE_FILE" 2>/dev/null || cat "$STATE_FILE"
    else
        echo "No active session."
    fi
    echo ""
    echo "=== ckpt Status ==="
    ckpt steps 2>/dev/null || echo "No active ckpt session."
}

help() {
    cat <<EOF
OCR Session Tool — wraps ckpt + tracking files

Usage: session.sh <command> [args]

Commands:
  start "goal"       Start a new session with a goal
  snap "message"     Create checkpoint + prompt to update SESSION.md
  sync               Sync ckpt state to CHECKPOINTS.md + STATE.json
  decide "t" "r" "a" Log a decision (title, rationale, alternatives)
  end                End session, append to LOG.md, squash ckpt
  status             Show current session state
  help               Show this message

Protocol: see PROTOCOL.md in the tracking directory.
EOF
}

case "${1:-help}" in
    start) shift; start_session "$@" ;;
    snap) shift; snap "$@" ;;
    sync) sync_checkpoints ;;
    decide) shift; decide "$@" ;;
    end) end_session ;;
    status) status ;;
    help|--help|-h) help ;;
    *) echo "Unknown command: $1"; help; exit 1 ;;
esac
